name: lmp-lite
channels:
  - conda-forge
dependencies:
  - python=3.13
  - fastapi
  - uvicorn
  - sqlalchemy
  - pydantic
  - python-dotenv
  - requests
  - pymysql
  - psycopg2
  - mysql-connector-python
  - pandas
  - geopandas
  - shapely
  - matplotlib
  - openpyxl
